# Secret for TatuScan sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: tatuscan-secrets
  namespace: tatuscan
type: Opaque
stringData:
  # Default SQLite database - uncomment and modify for PostgreSQL/MySQL
  # SQLALCHEMY_DATABASE_URI: "postgresql://user:pass@host:5432/tatuscan"
  SECRET_KEY: "change-this-secret-key-in-production"